material: ReS2_sim
description: "StackDiff comparison on the four PGDGAN image examples"

runtime:
  gpu: 2

sampling:
  batch_size: 1
  T_sampling: 100
  time_travel:
    enable: true
    travel_length: 1
    travel_repeat: 1

separation:
  num_layers: 2
  method: separate_sum
  eta: 0.85
  sigma_y: 0.
  simplified: true
  adaptive_superposition: true
  residual_debug: false

processing:
  auto_crop:
    enabled: false
  sliding_window: false

paths:
  model_checkpoint: "models/checkpoints/ReS2_online/ema_0.9999_200000.pt"
  input: "pgdgan/image"
  output: "SI/ddnm_separation/pgdgan_image_diffusion_result"
