material: ReS2_sim
description: "DDNM vs GAN comparison on simulated ReS2"

runtime:
  gpu: 2

sampling:
  batch_size: 1
  T_sampling: 100
  time_travel:
    enable: true
    travel_length: 1
    travel_repeat: 1

separation:
  num_layers: 2
  method: separate_sum
  eta: 0.85
  sigma_y: 0.
  simplified: true
  adaptive_superposition: true
  residual_debug: false

processing:
  auto_crop:
    enabled: false
  sliding_window: false

paths:
  model_checkpoint: "models/checkpoints/ReS2_online/ema_0.9999_200000.pt"
  default_input: "SI/ddnm_separation/comparison_input"
  default_output: "SI/ddnm_separation/comparison_result"
